[project]
name = "continuous-magnification-sampling"
version = "0.1.0"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["dataloaders", "evaluate_benchmarks"]

[tool.setuptools.packages.find]
where = ["."]